version: '3'
services:
  go-pausalac:
    build: .
    image: go-pausalac
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/pausalac
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mongodb_pausalac
    networks:
      - go-network

  mongodb_pausalac:
    image: mongo:latest
    container_name: mongodb_pausalac
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
    networks:
      - go-network

volumes:
  mongodbdata:

networks:
  go-network:
    driver: bridge
